from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, EmailStr
from langchain_core.messages import HumanMessage
from app.agent.graph import jarvis_agent
from app.services.supabase_client import save_chat_message, get_chat_history

router = APIRouter(prefix="/chat", tags=["Jarvis Chat"])

class ChatRequest(BaseModel):
    user_email: EmailStr
    message: str

class ChatResponse(BaseModel):
    reply: str

@router.get("/history")
def chat_history(user_email: EmailStr):
    return {"history": get_chat_history(user_email)}

@router.post("")
def chat_with_jarvis(req: ChatRequest):
    initial_state = {
        "messages": [HumanMessage(content=f"User Email: {req.user_email}\nMessage: {req.message}")],
        "user_email": req.user_email
    }

    try:
        # Non-streaming fallback / instant invoke
        result = jarvis_agent.invoke(initial_state)
        reply = result["messages"][-1].content

        # Persist both sides of the exchange. Best-effort: a logging
        # failure here shouldn't break the chat reply itself.
        try:
            save_chat_message(req.user_email, "user", req.message)
            save_chat_message(req.user_email, "assistant", reply)
        except Exception:
            import traceback
            traceback.print_exc()

        return {"reply": reply}
    except Exception as e:
        # Return a real JSON error instead of letting FastAPI's default
        # handler send plain text — the frontend does res.json() on this
        # response, which throws on non-JSON and shows a generic
        # "could not connect" message that hides the actual cause.
        import traceback
        traceback.print_exc()
        return {"reply": f"Jarvis hit an error processing that request: {e}"}


@router.post("/stream")
async def chat_stream_with_jarvis(req: ChatRequest):
    initial_state = {
        "messages": [HumanMessage(content=f"User Email: {req.user_email}\nMessage: {req.message}")],
        "user_email": req.user_email
    }

    async def event_generator():
        # Stream chunks as they are generated by LangGraph / LangChain
        async for event in jarvis_agent.astream_events(initial_state, version="v2"):
            if event["event"] == "on_chat_model_stream":
                chunk = event["data"]["chunk"].content
                if chunk:
                    yield f"data: {chunk}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")