from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, EmailStr
from langchain_core.messages import HumanMessage
from app.agent.graph import jarvis_agent

router = APIRouter(prefix="/chat", tags=["Jarvis Chat"])

class ChatRequest(BaseModel):
    user_email: EmailStr
    message: str

class ChatResponse(BaseModel):
    reply: str

@router.post("")
def chat_with_jarvis(req: ChatRequest):
    initial_state = {
        "messages": [HumanMessage(content=f"User Email: {req.user_email}\nMessage: {req.message}")],
        "user_email": req.user_email
    }
    
    # Non-streaming fallback / instant invoke
    result = jarvis_agent.invoke(initial_state)
    return {"reply": result["messages"][-1].content}


@router.post("/stream")
async def chat_stream_with_jarvis(req: ChatRequest):
    initial_state = {
        "messages": [HumanMessage(content=f"User Email: {req.user_email}\nMessage: {req.message}")],
        "user_email": req.user_email
    }

    async def event_generator():
        # Stream chunks as they are generated by LangGraph / LangChain
        async for event in jarvis_agent.astream_events(initial_state, version="v2"):
            if event["event"] == "on_chat_model_stream":
                chunk = event["data"]["chunk"].content
                if chunk:
                    yield f"data: {chunk}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")